const CurriculumActionsTypes = {
    FETCH_CURRICULUM_START: 'FETCH_CURRICULUM_START',
    FETCH_CURRICULUM_SUCCESS: 'FETCH_CURRICULUM_SUCCESS',
    FETCH_CURRICULUM_FAILURE: 'FETCH_CURRICULUM_FAILURE'
};

export default CurriculumActionsTypes;