const DropdownsActionTypes = {
    TOGGLE_SUBJECT_MENU: 'TOGGLE_SUBJECT_MENU',
    TOGGLE_HOME_MENU: 'TOGGLE_HOME_MENU',
    TOGGLE_SETTINGS_MENU: 'TOGGLE_SETTINGS_MENU',
    CLOSE_SUBJECT_MENU: 'CLOSE_SUBJECT_MENU',
    CLOSE_HOME_MENU: 'CLOSE_HOME_MENU',
    CLOSE_SETTINGS_MENU: 'CLOSE_SETTINGS_MENU',
    TOGGLE_SEARCH_MENU: 'TOGGLE_SEARCH_MENU',
    CLOSE_SEARCH_MENU: 'CLOSE_SEARCH_MENU',
    TOGGLE_MODAL_UP: 'TOGGLE_MODAL_UP'
};

export default DropdownsActionTypes;