// create user action types object
const UserActionTypes = {
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    UPDATE_USER_EMAIL_START: 'UPDATE_USER_EMAIL_START',
    UPDATE_USER_EMAIL_SUCCESS: 'UPDATE_USER_EMAIL_SUCCESS',
    UPDATE_USER_EMAIL_FAILURE: 'UPDATE_USER_EMAIL_FAILURE',
    RESET_EMAIL_CHANGED_TO_FALSE: 'RESET_EMAIL_CHANGED_TO_FALSE',
    UPDATE_USER_NAME_START: 'UPDATE_USER_NAME_START',
    UPDATE_USER_NAME_SUCCESS: 'UPDATE_USER_NAME_SUCCESS',
    UPDATE_USER_NAME_FAILURE: 'UPDATE_USER_NAME_FAILURE',
    RESET_NAME_CHANGED_TO_FALSE: 'RESET_NAME_CHANGED_TO_FALSE'
};

export default UserActionTypes