const SubjectActionsTypes = {
    FETCH_SUBJECTS_START: 'FETCH_SUBJECTS_START',
    FETCH_SUBJECTS_SUCCESS: 'FETCH_SUBJECTS_SUCCESS',
    FETCH_SUBJECTS_FAILURE: 'FETCH_SUBJECTS_FAILURE'
};

export default SubjectActionsTypes;